pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
  path('', HomePageView.as_view(), name='home'),
  path('about/', AboutPageView.as_view(), name='about'),
]

rahimia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('students/',  include('students.urls')),
    path('teachers/',  include('teachers.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import StudentListView, StudentDetailView

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    path('<uuid:pk>', StudentDetailView.as_view(), name='student_detail'),
    
    # ? Ajax Calls
]

administrative_divisions/models.py
import uuid
from django.db import models

# Create your models here.


class Province(models.Model):
    id = models.UUIDField(
        editable=False,
        primary_key=True,
        default=uuid.uuid4
    )
    name = models.CharField(max_length=30)
    president = models.CharField(max_length=60, default='')

    def __str__(self) -> str:
        return self.name


class Region(models.Model):
    id = models.UUIDField(
        editable=False,
        primary_key=True,
        default=uuid.uuid4
    )
    name = models.CharField(max_length=30)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    president = models.CharField(max_length=60, default='')

    def __str__(self) -> str:
        return self.name


class Zone(models.Model):
    id = models.UUIDField(
        editable=False,
        primary_key=True,
        default=uuid.uuid4
    )
    name = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    president = models.CharField(max_length=60, default='')

    def __str__(self) -> str:
        return self.name


class City(models.Model):
    id = models.UUIDField(
        editable=False,
        primary_key=True,
        default=uuid.uuid4
    )
    name = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    president = models.CharField(max_length=60, default='')

    def __str__(self) -> str:
        return self.name


class Halqa(models.Model):
    id = models.UUIDField(
        editable=False,
        primary_key=True,
        default=uuid.uuid4
    )
    name = models.CharField(max_length=30)
    zone = models.ForeignKey(Zone, on_delete=models.CASCADE)
    president = models.CharField(max_length=60, default='')


    def __str__(self) -> str:
        return self.name


class Responsibility(models.Model):
    pass

students/models.py
import uuid

from django.db import models
from administrative_divisions.models import Halqa, Responsibility
from django.utils.translation import gettext_lazy as _

from django.urls import reverse


class Student(models.Model):
    id = models.UUIDField(
        editable=False,
        primary_key=True,
        default=uuid.uuid4
    )
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30, default=None, blank=True)
    last_name = models.CharField(max_length=30)

    picture = models.ImageField(
        default="default/blank_profile.webp", upload_to="images/profile", blank=True)

    father_first_name = models.CharField(max_length=30)
    father_middle_name = models.CharField(
        max_length=30, default=None, blank=True)
    father_last_name = models.CharField(max_length=30)

    date_of_birth = models.DateField()
    date_of_registration = models.DateField()

    CNIC = models.CharField(max_length=13)
    CNIC_picture = models.ImageField(
        default="default/blank_cnic.jpg", upload_to="images/CNIC", blank=True)
    phone = models.CharField(max_length=11)

    education = models.CharField(max_length=300)
    occupation = models.CharField(max_length=300)

    current_address = models.CharField(max_length=300)
    permanent_address = models.CharField(max_length=300)

    halqa = models.ForeignKey(Halqa, on_delete=models.CASCADE, default=None)
    active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        return reverse('student_detail', args=[str(self.id)])



class Evaluation_A(models.Model):
    student = models.OneToOneField(Student, verbose_name=_("فارم الیف"), on_delete=models.CASCADE)
    interest_study = models.CharField(max_length=100)
    hold_of_ideology = models.CharField(max_length=100)
    punctuality = models.CharField(max_length=100)
    questioning = models.CharField(max_length=100)
    understanding_stubborn = models.CharField(max_length=100)
    ability_to_expression_of_thoughts = models.CharField(max_length=100)
    social_behaviour = models.CharField(max_length=100)
    discussion = models.CharField(max_length=500)

class Evaluation_B(models.Model):
    student = models.OneToOneField(Student, verbose_name=_("فارم ب"), on_delete=models.CASCADE)
    responsibility = models.ForeignKey(Responsibility, on_delete=models.SET_NULL, null=True)
    management_performance=models.CharField(max_length=100)
    project=models.CharField(max_length=100) # update Foreign
    discussion = models.CharField(max_length=500)

class Evaluation_C(models.Model):
    student = models.OneToOneField(Student, verbose_name=_("فارم ج"), on_delete=models.CASCADE)
    interest_study = models.CharField(max_length=100)
    social_behaviour = models.CharField(max_length=100)
    general_behaviour = models.CharField(max_length=100)
    participation_in_preaching = models.CharField(max_length=100)
    project=models.CharField(max_length=100)    # update Foreign
    resullt = models.BooleanField(default=True)

students/views.py
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DetailView, FormView

from .models import Student
from administrative_divisions.models import Halqa, Zone, Region, Province


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'students/student_list.html'
    context_object_name = "students"
    login_url = 'account_login'    
    
    
    def load_regions(self):
        province_id = self.request.GET.get('id_province')
        regions = Region.objects.filter(province_id=province_id)
        # cities = City.objects.filter(country_id=country_id).order_by('name')
        # return render(request, 'hr/city_dropdown_list_options.html', {'cities': cities})
        
    def get_queryset(self):
        return Student.objects.all()
    
class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    context_object_name = "student"
    template_name = 'students/student_detail.html'
    login_url = 'account_login'

templates/students/student_detail.html
{% extends "_base.html" %} {% block title %} Student {{ student.first_name }} {{
student.last_name }} {% endblock %} {% block content %}
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-7">
      <div class="card p-3 py-4">
        <div class="text-center">
          <img
            src="{{ student.picture.url }}"
            alt="Profile Picture"
            width="100px"
            class="rounded-circle"
          />
        </div>

        <div class="mx-5 p-5">
          <table class="table">
            <tbody>
              <tr>
                <td><b>Name</b></td>
                <td>
                  {{ student.first_name}} {{ student.middle_name}} 
                  {{ student.last_name }}
                </td>
              </tr>
              <tr>
                <td><b>Father Name</b></td>
                <td>
                  {{ student.father_first_name}} {{ student.father_middle_name}}
                  {{ student.father_last_name }}
                </td>
              </tr>
              <tr>
                <td><b>Date Of Birth</b></td>
                <td>{{student.date_of_birth}}</td>
              </tr>
              <tr>
                <td><b>Date Of registration</b></td>
                <td>{{student.date_of_registration}}</td>
              </tr>
              <tr>
                <td><b>CNIC</b></td>
                <td>{{student.CNIC}}</td>
              </tr>
              <tr>
                <td><b>CNIC Picture</b></td>
                <td>
                  <img
                    src="{{student.CNIC_picture.url}} "
                    width="350"
                    alt="cnic pic"
                  />
                </td>
              </tr>
              <tr>
                <td><b>Phone</b></td>
                <td>{{student.phone}}</td>
              </tr>
              <tr>
                <td><b>education</b></td>
                <td>{{student.education}}</td>
              </tr>
              <tr>
                <td><b>Occupation</b></td>
                <td>{{student.occupation}}</td>
              </tr>
              <tr>
                <td><b>current Address</b></td>
                <td>{{student.current_address}}</td>
              </tr>
              <tr>
                <td><b>Permanent Address</b></td>
                <td>{{student.permanent_address}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/students/student_list.html
{% extends "_base.html" %} {% block title %} students List {% endblock %} 
{% block search %}
<form class="form-inline mt-2 mt-md-0" action="." method="GET">
  <h2>Filter</h2>
  <div class="row border border-3 p-2">

    <div class="form-group col-3 my-2">
      <label for="id_first_name">first name:</label>
      <input type="text" name="first_name" class="form-control"  id="id_first_name">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_last_name">last name:</label>
      <input type="text" name="last_name" class="form-control"  id="id_last_name">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_father_first_name">father first name:</label>
      <input type="text" name="father_first_name" class="form-control"  id="id_father_first_name">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_father_last_name">father last name:</label>
      <input type="text" name="father_last_name" class="form-control"  id="id_father_last_name">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_phone">Phone:</label>
      <input type="tel" name="phone" class="form-control"  id="id_phone">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_cnic">CNIC:</label>
      <input type="tel" name="cnic" class="form-control"  id="id_cnic">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_date_of_birth">date of birth:</label>
      <input type="date" name="date_of_birth" class="form-control"  id="id_date_of_birth">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_date_of_registration">Date of Registration:</label>
      <input type="date" name="date_of_registration" class="form-control"  id="id_date_of_registration">
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_province">halqa:</label>
      <select name="province" class="form-control" id="id_province">

</select>
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_region">halqa:</label>
      <select name="region" class="form-control" id="id_region">
</select>
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_zone">Zone:</label>
      <select name="zone" class="form-control" id="id_zone">
</select>
    </div>
    
    <div class="form-group col-3 my-2">
      <label for="id_halqa">halqa:</label>
      <select name="halqa" class="form-control" id="id_halqa">
</select>
    </div>
    
    <div class="form-group col-6 my-3">
      <button class="btn btn-secondary w-50">Filter</button>
    </div>
  </div>
</form>
{% endblock search %}
{% block content %}

  {% if students %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">NO.</th>
        <th scope="col">Name</th>
        <th scope="col">Father Name</th>
        <th scope="col">Phone Number</th>
        <th scope="col">CNIC</th>
        <th scope="col">Date OF Birth</th>
        <th scope="col">Date Of Registration</th>

        <th scope="col">Halqa</th>
        <th scope="col">Zone</th>
        <th scope="col">Region</th>
        <th scope="col">Province</th>
        <th scope="col">Profile</th>
      </tr>
    </thead>
    <tbody>
      <p>{{ user.halqa }}</p> 
      {% for student in students%}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ student.first_name }} {{ student.last_name}}</td>
        <td>{{ student.father_first_name }} {{ student.father_last_name}}</td>
        <td>{{ student.phone }}</td>
        <td>{{ student.CNIC }}</td>
        <td>{{ student.date_of_birth }}</td>
        <td>{{ student.date_of_registration }}</td>

        <td>{{ student.halqa }}</td>
        <td>{{ student.halqa.zone }}</td>
        <td>{{ student.halqa.zone.region }}</td>
        <td>{{ student.halqa.zone.region.province }}</td>
        <td>
          <a class="btn btn-success" href="{{ student.get_absolute_url }}"
            >Profile</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <h4 class="text-center display-3">No Students was Found ...</h4>
  {% endif %}
{% endblock %}